sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-031
env:
  global:
    -
      # LTD_AWS_ID
      secure: m1i+etkmHlwXmfn/mRiPEhQMfxbd6n2n/ZkVBk1zwkvrdYtC88hgu+IKDPTc+v5xr2oqMvVlAWx+N9tfvQgP1vPEL2m2Uk+6DlcfyQnw2kqMeIzvayYOGK4guIbVD51GJOYSgQZMofjlR4XIS3nQhpxrmQf79PYcRwEnvu8P8ni8LPl+aNpT+7jjFuecmlIarMT4q3ESSL6I4j0QdhWi7HyprrRES3BXJbfRJ1fob0XET/k/K8+rlId07pZNrRG/3TNs4G6z5RyWl4ervzJ+XvZNH3P0ZzWisPz9o3ATBTWUTDQzHk2ovV9O/nywkZvG8FIu8wrqY6gd507SIhhhHorMhHvBLplwC/ttLqwt/mmcOzDKCsfgilEfPl2QmyhTjtDp8TNf4BBc1DeKSC8j80ft1OVoVcKYTSDVl7I+Aq6sLKqta9oq9EtsCwHqYE/btn4sTwI4+rWqXZGZ76J/MviaipLMY7q23+Epmbzq9YLtSVKOP5pgar2WcG1LhRIZ1pA0XagBPXIreJD7NMqPBLSZtKvHCyUNzWfa/nuaICXSvPhQjR5bZbiF8/alhZpM+USJNt5gO9S/DY8M6RFuD5Lc0Ginxpo4K/oyVllg+Dzpf33ttN89oIjQDeaf2NKCC469M0Kk36Sxnz4Av5CH9aUOf4QIzxsVFifI05/PJEA=
    -
      # LTD_AWS_SECRET
      secure: VSF1o0Kbj/ltUvdGpRnCetWaychNJZ4HPSbc7I0BaYpcuyTKTwFNZ9+N5+BUvQB09HNqTvJxG9yoiVxRRObpdG93XW1v1cxwo4qnTIUXM9CCzHC4Huh18o6TflFUXWqx0ucEzu4poPCruhvv4xZZ77a6Sk1mWEIw3esWesAYBIqjoI7/rVuM1OleiQ2L0oJBmuLq8f1CpUKuX8EQuu1XgwFPZF4MLpcMuARNvvFHCyJLVtQauGCKdUM5Oj2eWIUp7ctaFC6buCQUoupBD+XCXBq+98dLKK+urdUvxVbvhoRCzwJJoE8WYC87fwhJwx1yHaMVQpKXFztTJPz7CUgPu0ZV55330eeBbtNIrA+m7LS5tikmWBkNieNjrp8lspGs3RPAIlG26SzxfL0GEBVvhGDlzr+1LPLU43uHXl1NVAtjhDm4qpZRNChmF91RiqVMGkdMBrlQPgSWAy3mF7YHDiF/2uqx82SxAB6ZqljfE4uEnIsJbNqTOWZsRyARrmcNwxzgCI01dPhRfSZunxuAu64OvPf6OkCnozl6L9FuQKFXtc33iFAVUDhyjaxp61JhVOW2IqsgHjdBsSIXBLk+hkoWLqY3hj+88gJvj+St02L+ma/9q4bQsl+9AEWojRtlDXSEMe8m7ePp7RskgyFoegMG4sjSPbR6G42HLs8bX8Q=
    -
      # LTD_USERNAME
      secure: laLePT3djiRRJRcIfwhqhZHIyNrYY0d8M7G3GaxMTZTw8smmzBqh1XMU9mjL/VTMGA7aNcoyy8sW0X6F/ZSZfrWEABh5mNHXmEHvOf//LwYrR2qMVk/KfH6BTWXRxyXLnNoWFR0Euh1FtnNHGVq1kWmi/eWWIaWCvuwEpgIfZ2XXmBoQc7f3oU0VyjIUxlOjB6k3M1U3s0u+9crw77n6YS/JGgsdW4/+AOxqqZv4YyN/808RT17RTI1E27aywwjxVSoZkXSU5V523RPRmK0zhLj7offivanZ4bXcsgHrUKDK7kMSRdVIN8QvH2QHysOfy8tatVXjlOHyo8Q1g+doSkxp8X8Vn4HfR5ynuOStvX2Xa2yAvaFHp6iPKI2sRV7vFipe9jwG8VbAy4iZS8Fip/+4wIf+sALH7x4wmQoImlgG944B21y1hnn0Oy0KYnAEZ7pLiive8LKg6eA9+Kmy7ZOcTMGeOu/mB7mP3N5buDmx0ilmdCrAsyEgxyAZKK5MIrbodrDdre7nLhBQ44Qz7bN2r5VgC0bvbODO5MFTSjCwvsIc8YxNa8s7/CwHX4rY/uOkx/8j76GxtVWHRdOFEWP0h/e0K5sWub6jqOp26u/GVT1y/bBySHEqZ1uq/UfKHdf/vxgrRyvI4S1SIu7w5QH4G49Ammk8swLHYDd1pNY=
    -
      # LTD_PASSWORD
      secure: AKK5My6Mhk8c22jC1YaH+jhpl233eNIVNA7icInP15QRh36EkiPphNdmCzN/sJtY+h42ooM86BMsY0INevQSThXd5u9L5TRmbSi23aO2pmtaC2gecp+n9gm259WPoZnki6xvGG8Wkxb1muLYmmtcRKFKI7udGxHAPCwW/aQeCiaCVnLrC+JqdPl0y/1IDdf+5g5BBymMKKgHapG0XXUGQdS/AEPsXMeYqAsjj8m1BuxA3JmYNIRCsPEMbYHRjqzzRXl21GyBVXlQtC/C9mcd99jsSKhLqcUbl1oDf2RcGK2ZI+k2vXk2+qqFZV8zDD1HpYEvhVPBYaEyTY5cXnG3Jj417pMp9Rj1cQc/DwIWxHl/7i/ap6q3IGdZ/B30ioMtffIy9Uf/L3klraYvNnUFbGO/MtBaNyDsEG7CbbUHgZbYQ5z+I2xLP9xfIpR6vX3sx+pKsORFaJ2O56FpkV+3RxYFXkrIwXgQH+An86C0kP6yEDgTFBhZYA5CnotnkNCsxoQh7xycpv8mW8uNIGIDvgznA/Xwf/PEbQ56+lwZq0TMBq42lPj8lK4giIB52BpJKWzkIR/zmDx78MzygsPQ6EZ1wujSpC9VJYaPclaGTSmMsJCdurPbkRSNI/W14p+tftjJyiZ7M1N8ZZWQWVHuXQUhGzEMNfOptSl3iWi5jyc=
